"""Mock LLM provider for local testing / load tests."""

from __future__ import annotations

import asyncio
import json

from .base import LLMProvider


class MockProvider(LLMProvider):
    """Simple deterministic provider that avoids external LLM calls."""

    async def complete(self, prompt: str, system_prompt: Optional[str] = None, response_format: Optional[dict] = None) -> str:  # noqa: ARG002
        await asyncio.sleep(0)  # keep signature async-friendly
        fake_response = {
            "product": {"name": "Mock Product", "category": "mock_category", "description": "Generated by MockProvider"},
            "technical_specs": {"duration": 20, "aspect_ratio": "9:16", "platform": "tiktok", "resolution": "1080x1920"},
            "visual_direction": {"aesthetic": "mock", "style_source": "text"},
            "scenes": [
                {
                    "id": "scene_1",
                    "scene_number": 1,
                    "start_time": 0.0,
                    "duration": 5.0,
                    "purpose": "hook",
                    "visual": {"shot_type": "medium_shot", "generation_prompt": "mock scene"},
                }
            ],
        }
        return json.dumps(fake_response)

    async def analyze_image(self, image_data: bytes, question: str) -> dict:  # noqa: ARG002
        await asyncio.sleep(0)
        return {
            "dominant_colors": ["#FFFFFF"],
            "lighting": "mock",
            "mood": "mock",
        }

    async def is_available(self) -> bool:
        return True

    def get_estimated_latency(self) -> int:
        return 50

