"""
Core infrastructure for the generation platform.
"""
from .types import (
    EngineType,
    ImageProvider,
    VideoProvider,
    AudioProvider,
    PromptProvider,
    TaskStatus,
    ImageModel,
    ImageSize,
    AspectRatio,
    VideoModel,
    VideoDuration,
    AudioModel,
    AudioDuration,
    AssetType,
    ExecutionMode,
)

from .exceptions import (
    PlatformException,
    AuthenticationError,
    AuthorizationError,
    ValidationError,
    InvalidParameterError,
    MissingParameterError,
    NotFoundError,
    ResourceNotFoundError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    GenerationError,
    ProviderError,
    TaskNotReadyError,
    TaskFailedError,
    TaskCanceledError,
    StorageError,
    FileNotFoundError,
    FileUploadError,
    FileTooLargeError,
    InvalidFileTypeError,
    PipelineError,
    PipelineValidationError,
    PipelineExecutionError,
    CircularDependencyError,
    DatabaseError,
    DatabaseConnectionError,
    TransactionError,
    RateLimitError,
    ExternalServiceError,
    ConfigurationError,
)

from .models import (
    BaseRequest,
    BaseResponse,
    Task,
    PaginatedResponse,
    ErrorResponse,
    HealthResponse,
    AssetBase,
    BaseFilter,
    TaskFilter,
)

from .database import (
    DatabaseManager,
    get_db_manager,
    get_db_connection,
)

from .middleware import (
    RequestLoggingMiddleware,
    ExceptionHandlerMiddleware,
    configure_middleware,
    configure_cors,
)

__all__ = [
    # Types
    "EngineType",
    "ImageProvider",
    "VideoProvider",
    "AudioProvider",
    "PromptProvider",
    "TaskStatus",
    "ImageModel",
    "ImageSize",
    "AspectRatio",
    "VideoModel",
    "VideoDuration",
    "AudioModel",
    "AudioDuration",
    "AssetType",
    "ExecutionMode",
    # Exceptions
    "PlatformException",
    "AuthenticationError",
    "AuthorizationError",
    "ValidationError",
    "InvalidParameterError",
    "MissingParameterError",
    "NotFoundError",
    "ResourceNotFoundError",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "GenerationError",
    "ProviderError",
    "TaskNotReadyError",
    "TaskFailedError",
    "TaskCanceledError",
    "StorageError",
    "FileNotFoundError",
    "FileUploadError",
    "FileTooLargeError",
    "InvalidFileTypeError",
    "PipelineError",
    "PipelineValidationError",
    "PipelineExecutionError",
    "CircularDependencyError",
    "DatabaseError",
    "DatabaseConnectionError",
    "TransactionError",
    "RateLimitError",
    "ExternalServiceError",
    "ConfigurationError",
    # Models
    "BaseRequest",
    "BaseResponse",
    "Task",
    "PaginatedResponse",
    "ErrorResponse",
    "HealthResponse",
    "AssetBase",
    "BaseFilter",
    "TaskFilter",
    # Database
    "DatabaseManager",
    "get_db_manager",
    "get_db_connection",
    # Middleware
    "RequestLoggingMiddleware",
    "ExceptionHandlerMiddleware",
    "configure_middleware",
    "configure_cors",
]
