module CreativeBriefEditor exposing (Model, Msg, init, update, view, subscriptions)

import Browser.Navigation as Nav
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)
import Http
import Json.Decode as Decode
import Json.Decode.Pipeline as Pipeline
import Json.Encode as Encode
import Route exposing (Route)
import Task
import File exposing (File)
-- import Bytes exposing (Bytes)  -- Not available
-- import Base64  -- Not available
import Ports


-- MODEL


type alias Model =
    { text : String
    , imageUrl : String
    , videoUrl : String
    , platform : String
    , category : String
    , llmProvider : String
    , isLoading : Bool
    , error : Maybe String
    , response : Maybe CreativeBriefResponse
    , selectedFile : Maybe File
    , briefId : Maybe String
    , autoScenePrompt : String
    , navigationKey : Nav.Key
    , imageModels : List ImageModel
    , selectedImageModel : Maybe String
    , loadingImageModels : Bool
    , generatingImages : Bool
    }


type alias ImageModel =
    { name : String
    , owner : String
    , description : String
    }


type alias CreativeBriefResponse =
    { status : String
    , creativeDirection : Decode.Value
    , scenes : List Scene
    , metadata : Metadata
    , briefId : String  -- Added for response
    }


type alias Scene =
    { id : String
    , sceneNumber : Int
    , purpose : String
    , duration : Float
    , visual : Maybe VisualDetails
    }


type alias VisualDetails =
    { shotType : Maybe String
    , subject : Maybe String
    , generationPrompt : Maybe String
    }


type alias Metadata =
    { cacheHit : Bool
    , confidenceScore : Maybe Float
    , autoGeneratedScene : Maybe Decode.Value
    }


type alias UploadResponse =
    { url : String
    , id : String
    }


type alias SceneResponse =
    { sceneId : String
    , prompt : String
    }


type alias VideoResponse =
    { videoId : String
    , status : String
    }


init : Nav.Key -> ( Model, Cmd Msg )
init key =
    ( { text = ""
      , imageUrl = ""
      , videoUrl = ""
      , platform = "tiktok"
      , category = "luxury"
      , llmProvider = "openrouter"
      , isLoading = False
      , error = Nothing
      , response = Nothing
      , selectedFile = Nothing
      , briefId = Nothing
      , autoScenePrompt = ""
      , navigationKey = key
      , imageModels = []
      , selectedImageModel = Nothing
      , loadingImageModels = True
      , generatingImages = False
      }
    , fetchImageModels
    )


-- UPDATE


type Msg
    = UpdateText String
    | UpdateImageUrl String
    | UpdateVideoUrl String
    | UpdatePlatform String
    | UpdateCategory String
    | UpdateLLMProvider String
    | SubmitBrief Bool  -- bypass_cache
    | BriefResponse (Result Http.Error CreativeBriefResponse)
    | ClearError
    | FileSelected File
    | FileLoaded String
    | UploadMedia
    | GotUpload (Result Http.Error UploadResponse)
    | GenerateScene
    | GotScene (Result Http.Error SceneResponse)
    | GenerateVideo
    | GotVideo (Result Http.Error VideoResponse)
    | RefineBrief
    | GotRefine (Result Http.Error CreativeBriefResponse)
    | NavigateTo Route
    | FetchImageModels
    | ImageModelsFetched (Result Http.Error (List ImageModel))
    | SelectImageModel String
    | GenerateImages
    | ImagesGenerated (Result Http.Error (List Int))


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        UpdateText text ->
            ( { model | text = text }, Cmd.none )

        UpdateImageUrl url ->
            ( { model | imageUrl = url }, Cmd.none )

        UpdateVideoUrl url ->
            ( { model | videoUrl = url }, Cmd.none )

        UpdatePlatform platform ->
            ( { model | platform = platform }, Cmd.none )

        UpdateCategory category ->
            ( { model | category = category }, Cmd.none )

        UpdateLLMProvider provider ->
            ( { model | llmProvider = provider }, Cmd.none )

        SubmitBrief bypass ->
            ( { model | isLoading = True, error = Nothing }
            , submitBrief model bypass
            )

        BriefResponse result ->
            case result of
                Ok response ->
                    let
                        firstScenePrompt =
                            List.head response.scenes
                                |> Maybe.andThen .visual
                                |> Maybe.andThen .generationPrompt
                                |> Maybe.withDefault ""
                    in
                    ( { model
                        | isLoading = False
                        , response = Just response
                        , briefId = Just response.briefId
                        , autoScenePrompt = firstScenePrompt
                        , error = Nothing
                      }
                    , Cmd.none
                    )

                Err error ->
                    ( { model
                        | isLoading = False
                        , error = Just (httpErrorToString error)
                      }
                    , Cmd.none
                    )

        ClearError ->
            ( { model | error = Nothing }, Cmd.none )

        FileSelected file ->
            ( { model | selectedFile = Just file }, Cmd.none )

        FileLoaded base64 ->
            ( model, uploadMedia model base64 )

        UploadMedia ->
            ( model, Ports.requestFileRead () )

        GotUpload result ->
            case result of
                Ok uploadResponse ->
                    let
                        -- Determine if uploaded file was image or video based on URL
                        updatedModel =
                            if String.contains "image" uploadResponse.url then
                                { model | imageUrl = uploadResponse.url, error = Nothing }
                            else
                                { model | videoUrl = uploadResponse.url, error = Nothing }
                    in
                    ( updatedModel, submitBrief updatedModel False )

                Err error ->
                    ( { model | error = Just (httpErrorToString error) }, Cmd.none )

        GenerateScene ->
            case model.briefId of
                Just id ->
                    ( { model | isLoading = True }, generateScene id model.autoScenePrompt model.llmProvider )

                Nothing ->
                    ( model, Cmd.none )

        GotScene result ->
            case result of
                Ok _ ->
                    ( { model | isLoading = False }, Nav.pushUrl model.navigationKey "/simulations" )

                Err error ->
                    ( { model | isLoading = False, error = Just (httpErrorToString error) }, Cmd.none )

        GenerateVideo ->
            case model.briefId of
                Just id ->
                    ( { model | isLoading = True }, generateVideo id )

                Nothing ->
                    ( model, Cmd.none )

        GotVideo result ->
            case result of
                Ok _ ->
                    ( { model | isLoading = False }, Nav.pushUrl model.navigationKey "/videos" )

                Err error ->
                    ( { model | isLoading = False, error = Just (httpErrorToString error) }, Cmd.none )

        RefineBrief ->
            case model.briefId of
                Just id ->
                    ( { model | isLoading = True }, refineBrief id model.text )

                Nothing ->
                    ( model, Cmd.none )

        GotRefine result ->
            case result of
                Ok response ->
                    ( { model
                        | isLoading = False
                        , response = Just response
                        , error = Nothing
                      }
                    , Cmd.none
                    )

                Err error ->
                    ( { model
                        | error = Just (httpErrorToString error)
                      }
                    , Cmd.none
                    )

        NavigateTo route ->
            ( model, Nav.pushUrl model.navigationKey (Route.toHref route) )


-- HTTP


submitBrief : Model -> Bool -> Cmd Msg
submitBrief model bypass =
    let
        url = "/api/creative/parse" ++ (if bypass then "?bypass_cache=true" else "")
        body =
            Encode.object
                [ ( "prompt"
                  , Encode.object
                        [ ( "text", Encode.string model.text )
                        , ( "image_url"
                          , if String.isEmpty model.imageUrl then
                                Encode.null
                            else
                                Encode.string model.imageUrl
                          )
                        , ( "video_url"
                          , if String.isEmpty model.videoUrl then
                                Encode.null
                            else
                                Encode.string model.videoUrl
                          )
                        , ( "platform", Encode.string model.platform )
                        , ( "category", Encode.string model.category )
                        ]
                  )
                , ( "options"
                  , Encode.object
                        [ ( "llm_provider", Encode.string model.llmProvider )
                        , ( "include_cost_estimate", Encode.bool False )
                        ]
                  )
                ]
        expect =
            Http.expectJson BriefResponse decodeBriefResponse
    in
    Http.post
        { url = url
        , body = Http.jsonBody body
        , expect = expect
        }


decodeVisualDetails : Decode.Decoder VisualDetails
decodeVisualDetails =
    Decode.map3 VisualDetails
        (Decode.maybe (Decode.field "shot_type" Decode.string))
        (Decode.maybe (Decode.field "subject" Decode.string))
        (Decode.maybe (Decode.field "generation_prompt" Decode.string))


decodeMetadata : Decode.Decoder Metadata
decodeMetadata =
    Decode.map3 Metadata
        (Decode.field "cache_hit" Decode.bool)
        (Decode.maybe (Decode.field "confidence_score" Decode.float))
        (Decode.maybe (Decode.field "auto_generated_scene" Decode.value))


decodeBriefResponse : Decode.Decoder CreativeBriefResponse
decodeBriefResponse =
    Decode.map5 CreativeBriefResponse
        (Decode.field "status" Decode.string)
        (Decode.field "creative_direction" Decode.value)
        (Decode.field "scenes" (Decode.list decodeScene))
        (Decode.field "metadata" decodeMetadata)
        (Decode.field "briefId" Decode.string)


decodeScene : Decode.Decoder Scene
decodeScene =
    Decode.map5 Scene
        (Decode.field "id" Decode.string)
        (Decode.field "scene_number" Decode.int)
        (Decode.field "purpose" Decode.string)
        (Decode.field "duration" Decode.float)
        (Decode.maybe (Decode.field "visual" decodeVisualDetails))


httpErrorToString : Http.Error -> String
httpErrorToString error =
    case error of
        Http.BadUrl url ->
            "Bad URL: " ++ url

        Http.Timeout ->
            "Request timed out"

        Http.NetworkError ->
            "Network error"

        Http.BadStatus status ->
            "Bad status: " ++ String.fromInt status

        Http.BadBody message ->
            "Bad response: " ++ message


-- VIEW


view : Model -> Html Msg
view model =
    div [ style "padding" "20px", style "max-width" "800px", style "margin" "0 auto" ]
        [ h2 [] [ text "Creative Brief Editor" ]
        , if model.isLoading then
            div [ style "text-align" "center", style "color" "#666" ] [ text "Generating brief..." ]

          else
            div []
                [ Html.form []
                    [ div [ style "margin-bottom" "10px" ]
                        [ label [ style "display" "block", style "margin-bottom" "5px" ] [ text "Prompt Text" ]
                        , textarea
                            [ placeholder "Enter your creative prompt..."
                            , rows 5
                            , cols 50
                            , value model.text
                            , onInput UpdateText
                            , style "width" "100%", style "padding" "8px", style "border" "1px solid #ccc", style "border-radius" "4px"
                            ]
                            []
                        ]
                    , div [ style "display" "flex", style "gap" "20px", style "margin-bottom" "10px" ]
                        [ div []
                            [ label [ style "display" "block", style "margin-bottom" "5px" ] [ text "Platform" ]
                            , select [ onInput UpdatePlatform ]
                                [ option [ value "tiktok" ] [ text "TikTok" ]
                                , option [ value "instagram" ] [ text "Instagram" ]
                                ]
                            ]
                        , div []
                            [ label [ style "display" "block", style "margin-bottom" "5px" ] [ text "Category" ]
                            , select [ onInput UpdateCategory ]
                                [ option [ value "luxury" ] [ text "Luxury" ]
                                , option [ value "tech" ] [ text "Tech" ]
                                ]
                            ]
                        , div []
                            [ label [ style "display" "block", style "margin-bottom" "5px" ] [ text "LLM Provider" ]
                            , select [ onInput UpdateLLMProvider ]
                                [ option [ value "openai" ] [ text "OpenAI (GPT-4o)" ]
                                , option [ value "claude" ] [ text "Claude" ]
                                ]
                            ]
                        ]
                    , div [ style "margin-bottom" "10px" ]
                        [ input [ type_ "file", id "media-upload", accept "image/*,video/*" ] []
                        , button [ type_ "button", onClick UploadMedia, style "margin-left" "10px", style "padding" "8px 12px", style "background" "#4CAF50", style "color" "white", style "border" "none", style "border-radius" "4px" ] [ text "Upload Media" ]
                        ]
                    , button [ type_ "button", onClick (SubmitBrief False), style "background-color" "#4CAF50", style "color" "white", style "padding" "10px 16px", style "border" "none", style "border-radius" "4px", style "margin-right" "10px" ] [ text "Generate Brief" ]
                    , button [ type_ "button", onClick (SubmitBrief True), style "background-color" "#ff9800", style "color" "white", style "padding" "10px 16px", style "border" "none", style "border-radius" "4px" ] [ text "Generate (Bypass Cache)" ]
                    ]
                , case model.selectedFile of
                    Just file ->
                        p [ style "color" "#666", style "margin-top" "10px" ] [ text ("Selected: " ++ File.name file) ]

                    Nothing ->
                        text ""
                , case model.response of
                    Just response ->
                        div [ style "margin-top" "20px", style "border" "1px solid #ccc", style "padding" "15px", style "border-radius" "8px", style "background" "#f9f9f9" ]
                            [ h3 [] [ text "Generated Brief" ]
                            , p [] [ text ("ID: " ++ (Maybe.withDefault "Unknown" model.briefId)) ]
                            , case response.metadata.confidenceScore of
                                Just score ->
                                    p [] [ text ("Confidence: " ++ String.fromFloat score) ]
                                Nothing ->
                                    text ""
                            , h4 [] [ text "Creative Direction" ]
                            , pre [ style "background" "#f4f4f4", style "padding" "10px", style "border-radius" "4px", style "overflow-x" "auto" ] [ text (Encode.encode 2 response.creativeDirection) ]
                            , h4 [] [ text "Scenes" ]
                            , div [] (List.map viewScene response.scenes)
                            , if String.isEmpty model.autoScenePrompt then
                                text ""
                              else
                                div [ style "margin-top" "10px", style "padding" "10px", style "background" "#e8f5e8", style "border-radius" "4px" ]
                                    [ h4 [] [ text "Auto-Filled Scene Prompt" ]
                                    , p [] [ text model.autoScenePrompt ]
                                    , button [ onClick GenerateScene, style "background-color" "#2196F3", style "color" "white", style "padding" "8px 12px", style "border" "none", style "border-radius" "4px" ] [ text "Generate Scene" ]
                                    ]
                            , button [ onClick GenerateVideo, style "background-color" "#9C27B0", style "color" "white", style "padding" "10px 16px", style "border" "none", style "border-radius" "4px", style "margin-top" "10px" ] [ text "Generate Video from Brief" ]
                            , button [ onClick RefineBrief, style "background-color" "#f44336", style "color" "white", style "padding" "10px 16px", style "border" "none", style "border-radius" "4px", style "margin-left" "10px" ] [ text "Refine Brief" ]
                            ]

                    Nothing ->
                        text ""
                , case model.error of
                    Just err ->
                        div [ style "color" "red", style "margin-top" "10px", style "padding" "10px", style "background" "#ffebee", style "border-radius" "4px" ] [ text ("Error: " ++ err) ]

                    Nothing ->
                        text ""
                ]
        ]


viewForm : Model -> Html Msg
viewForm model =
    Html.form [ onSubmit (SubmitBrief False), class "brief-form" ]
        [ div [ class "form-group" ]
            [ label [ for "text" ] [ text "Prompt Text *" ]
            , textarea
                [ id "text"
                , value model.text
                , onInput UpdateText
                , placeholder "Describe your video concept..."
                , required True
                , rows 4
                ]
                []
            ]
        , div [ class "form-group" ]
            [ label [ for "imageUrl" ] [ text "Image URL" ]
            , input
                [ type_ "url"
                , id "imageUrl"
                , value model.imageUrl
                , onInput UpdateImageUrl
                , placeholder "https://example.com/image.jpg"
                ]
                []
            ]
        , div [ class "form-group" ]
            [ label [ for "videoUrl" ] [ text "Video URL" ]
            , input
                [ type_ "url"
                , id "videoUrl"
                , value model.videoUrl
                , onInput UpdateVideoUrl
                , placeholder "https://example.com/video.mp4"
                ]
                []
            ]
        , div [ class "form-row" ]
            [ div [ class "form-group" ]
                [ label [ for "platform" ] [ text "Platform" ]
                , select [ id "platform", onInput UpdatePlatform, value model.platform ]
                    [ option [ value "tiktok" ] [ text "TikTok" ]
                    , option [ value "instagram" ] [ text "Instagram" ]
                    , option [ value "youtube" ] [ text "YouTube" ]
                    ]
                ]
            , div [ class "form-group" ]
                [ label [ for "category" ] [ text "Category" ]
                , select [ id "category", onInput UpdateCategory, value model.category ]
                    [ option [ value "luxury" ] [ text "Luxury" ]
                    , option [ value "tech" ] [ text "Technology" ]
                    , option [ value "fashion" ] [ text "Fashion" ]
                    , option [ value "food" ] [ text "Food" ]
                    ]
                ]
            ]
        , button
            [ type_ "submit"
            , disabled model.isLoading
            , class "submit-btn"
            ]
            [ if model.isLoading then
                text "Generating..."
              else
                text "Generate Brief"
            ]
        ]


viewResponse : Model -> Html Msg
viewResponse model =
    case model.error of
        Just error ->
            div [ class "error-message" ]
                [ text error
                , button [ onClick ClearError ] [ text "×" ]
                ]

        Nothing ->
            case model.response of
                Just response ->
                    div [ class "brief-response" ]
                        [ h3 [] [ text "Generated Creative Brief" ]
                        , div [ class "brief-meta" ]
                            [ text ("Status: " ++ response.status)
                            , case response.metadata.confidenceScore of
                                Just score ->
                                    text (" | Confidence: " ++ String.fromFloat score)

                                Nothing ->
                                    text ""
                            ]
                        , div [ class "scenes-list" ]
                            (List.map viewScene response.scenes)
                        , case response.metadata.autoGeneratedScene of
                            Just scene ->
                                div [ class "auto-scene" ]
                                    [ h4 [] [ text "Auto-Generated Physics Scene" ]
                                    , text "A physics scene has been automatically generated from this brief."
                                    ]

                            Nothing ->
                                text ""
                        ]

                Nothing ->
                    text ""


viewScene : Scene -> Html Msg
viewScene scene =
    div [ class "scene-item" ]
        [ h4 [] [ text ("Scene " ++ String.fromInt scene.sceneNumber ++ ": " ++ scene.purpose) ]
        , div [ class "scene-details" ]
            [ text ("Duration: " ++ String.fromFloat scene.duration ++ "s")
            , case scene.visual of
                Just visual ->
                    case visual.generationPrompt of
                        Just prompt ->
                            div []
                                [ text "Generation Prompt: "
                                , text prompt
                                ]

                        Nothing ->
                            text ""

                Nothing ->
                    text ""
            ]
        ]

-- DECODERS FOR RESPONSES

decodeUploadResponse : Decode.Decoder UploadResponse
decodeUploadResponse =
    Decode.map2 UploadResponse
        (Decode.field "url" Decode.string)
        (Decode.field "id" Decode.string)


decodeSceneResponse : Decode.Decoder SceneResponse
decodeSceneResponse =
    Decode.map2 SceneResponse
        (Decode.field "sceneId" Decode.string)
        (Decode.field "prompt" Decode.string)


decodeVideoResponse : Decode.Decoder VideoResponse
decodeVideoResponse =
    Decode.map2 VideoResponse
        (Decode.field "videoId" Decode.string)
        (Decode.field "status" Decode.string)


-- HTTP FUNCTIONS

uploadMedia : Model -> String -> Cmd Msg
uploadMedia model base64 =
    let
        body =
            Encode.object
                [ ( "file", Encode.string base64 )
                , ( "type"
                  , if String.contains "image" base64 then
                        Encode.string "image"
                    else
                        Encode.string "video"
                  )
                ]
    in
    Http.post
        { url = "/api/upload"
        , body = Http.jsonBody body
        , expect = Http.expectJson GotUpload decodeUploadResponse
        }


generateScene : String -> String -> String -> Cmd Msg
generateScene briefId prompt provider =
    let
        body =
            Encode.object
                [ ( "briefId", Encode.string briefId )
                , ( "prompt", Encode.string prompt )
                , ( "llm_provider", Encode.string provider )
                ]
    in
    Http.post
        { url = "/api/generate"
        , body = Http.jsonBody body
        , expect = Http.expectJson GotScene decodeSceneResponse
        }


generateVideo : String -> Cmd Msg
generateVideo briefId =
    let
        body =
            Encode.object
                [ ( "briefId", Encode.string briefId )
                ]
    in
    Http.post
        { url = "/api/genesis/render"
        , body = Http.jsonBody body
        , expect = Http.expectJson GotVideo decodeVideoResponse
        }


refineBrief : String -> String -> Cmd Msg
refineBrief briefId refinementText =
    let
        body =
            Encode.object
                [ ( "refinement", Encode.string refinementText )
                ]
    in
    Http.post
        { url = "/api/creative/briefs/" ++ briefId ++ "/refine"
        , body = Http.jsonBody body
        , expect = Http.expectJson GotRefine decodeBriefResponse
        }


-- SUBSCRIPTIONS


subscriptions : Model -> Sub Msg
subscriptions model =
    Ports.fileLoaded FileLoaded
